config/routes.rb
GainesStreetFest::Application.routes.draw do
  
  match '/bands',   to: "site_pages#bands",   via: 'get'
  match '/aboutus',   to: "site_pages#aboutus",   via: 'get'
  match '/sponsors',   to: "site_pages#sponsors",   via: 'get'
  match '/merch',   to: "site_pages#merch",   via: 'get'
  match '/press',   to: "site_pages#press",   via: 'get'
  root "site_pages#home"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_pages_controller.rb
class SitePagesController < ApplicationController
  def bands
  end
  def home
    @band_list = "2 For A Dollar
Altar of Flesh
Antagonizers ATL
Attack Culture
Attack on Tortuga
Baccone Dolce
Bad Vibe
BAET
Black Cousins
Boo Radley
Breakup Hospital
Brown Goose, The
Chaotic Transit
Cobalt Rabbit
David Lareau and The Copperpots
Desgraciadas
Dix, The
Dreadship
Driving Lights
Father Feather
Flat Land
Fly By Night
Forever Ago
Form
Fotre
Fungle Junk
Fuzzhound
Gamble Cosmos
Hold That Hand
Horseshoes and Hand Grenades
Human Progress
Humanzii
kidDead
Kristin Cynthia
Leah and the Aviators
Lepro
Like Dinosaurs
Lingua Franca
Louis Meyerson
Mae West Band
Meatsweats
Naps
No Face
N. Skywalker
Ohligans
Plastic Dividers
Pleasant Peasant
Quiver
Robbin Thieves
Seattle Fucking Supersonics
Shorty the Giant
Shower Beers, The
Side Note
Snake Oil
Storm Craft
Success
Sunghosts
Sway Jah Vu
That Kid With a Guitar
Threshing
Traumahawk
Trial By Stone
Tygerdance
Wabbits, The
Wanderfoot
Young Deville"
  end
  def aboutus
  end
  def sponsors
  end
  def merch
  end
  def press
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_pages_helper.rb
module SitePagesHelper
end

app/views/layouts/_header.html.erb
<!-- <header>
	<div class="event-info animated fadeInUp ">
		<ul>
			<li >BEER</li>
			<li>FOOD</li>
			<li>MUSIC</li>
			<li>ART</li>
		</ul>

	<ul>
		<li>OCTOBER 11th, 2014</li>
		<li>GAINES STREET & RAILROAD AVE</li> 
	</ul>
		
	</div>
	<div class="logo animated"></div>
	
	<nav class="main-nav col-12 ">
		<ul class="center">
			<li class="col-2 animated fadeInLeft"></li>
			<li class="col-2 animated fadeInLeft"><%= nav_link_to "BANDS", bands_path %></li>
			<li class="col-2 animated fadeInLeft"><%= nav_link_to "SPONSORS",    sponsors_path %></li>
			<li class="col-2 animated fadeInLeft"><%= nav_link_to "MERCH",    merch_path %></li>
			<li class="col-2 animated fadeInLeft"><%= nav_link_to "PRESS",    press_path %></li>
		</ul>
	</nav>
</header> -->

<header>
	<div class="event-info left">
	<ul>
		<li>OCTOBER 11th, 2014</li>
		<li>GAINES STREET & RAILROAD AVE</li> 
	</ul>	
	</div>

	<nav class="right">
		<ul>
			<li>ABOUT US</li>
			<li>CONTACT</li>
		</ul>
	</nav>
	
	<div class="logo mx-auto"></div>
	
	<div class="top-info-bar col-12 ">
		<ul class="center">
			<li class="col-2">BEER</li>
			<li class="col-2 ">FOOD</li>
			<li class="col-2">MUSIC</li>
			<li class="col-2">ART</li>
		</ul>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GainesStreetFest</title>
  <%= stylesheet_link_tag "whole_site", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/site_pages/bands.html.erb
<h2>LINEUP</h2>

app/views/site_pages/home.html.erb
<h2>lineup</h2>

<div class="show-list col-10">
	
	<% @band_ok = @band_list.split("\n") %>
<% @band_ok.each do |i| %>
<li><%= i %></li>
<% end %>
</div>
<h2>schedule</h2>


<body>
<div class="schedule col-10 clearfix">
	<table class="table-fill left">
			<caption>ST. MICHEAL'S PUB</caption>
		<thead>
			<tr>
				<th class="text-left">Time</th>
				<th class="text-right">Band</th>
			</tr>
		</thead>
		<tbody class="table-hover">
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
		</tr>
		</tbody>
	</table>

	<table class="table-fill left">
			<caption>All Saint's cafe</caption>
		<thead>
			<tr>
				<th class="text-left">Time</th>
				<th class="text-right">Band</th>
			</tr>
		</thead>
		<tbody class="table-hover">
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
		</tr>
		</tbody>
	</table>

	<table class="table-fill left">
			<caption>All Saint's cafe</caption>
		<thead>
			<tr>
				<th class="text-left">Time</th>
				<th class="text-right">Band</th>
			</tr>
		</thead>
		<tbody class="table-hover">
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
		</tr>
		</tbody>
	</table>
	<table class="table-fill left">
			<caption>All Saint's cafe</caption>
		<thead>
			<tr>
				<th class="text-left">Time</th>
				<th class="text-right">Band</th>
			</tr>
		</thead>
		<tbody class="table-hover">
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
			</tr>
			<tr>
				<td class="text-left">1:50PM - 2:20PM</td>
				<td class="text-right">Father Feather</td>
		</tr>
		</tbody>
	</table>
</div>
<h2>sponsors</h2>

app/views/site_pages/merch.html.erb
hello	

app/views/site_pages/press.html.erb
<h1>press!!</h1>

app/views/site_pages/sponsors.html.erb
<h1>sponsors!!</h1>